# image: https://registry.hub.docker.com/r/apache/rocketmq
# image: https://registry.hub.docker.com/r/apacherocketmq/rocketmq-dashboard

version: '3.8'

services:
  namesrv:
    image: apacherocketmq/rocketmq:${APP_VERSION}
    container_name: ${APP_NAME}-namesrv
    ports:
      - 9876:9876
    volumes:
      - namesrv_log:/home/rocketmq/logs
    command: sh mqnamesrv
  broker:
    image: apacherocketmq/rocketmq:${APP_VERSION}
    container_name: ${APP_NAME}-broker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - broker_log:/home/rocketmq/logs
      - broker_store:/home/rocketmq/store
      - ./src/broker.conf:/opt/rocketmq-${APP_VERSION}/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-${APP_VERSION}/conf/broker.conf

  rocketmqgui:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: ${APP_NAME}-gui
    environment:
     - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    restart: always
    ports:
      - ${APP_PORT}:8080 
      
networks:
  default:
      name: ${APP_NAME}

volumes:
  namesrv_log:
  broker_log:
  broker_store:
